<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Categories extends MY_Controller {

    static $type = 'post';

    function __construct() {
        parent::__construct();
        $this->load->model('app/Categories_model');
        $this->load->model('app/Posts_model');
        $this->load->library('form_validation');
    }

    public function index() {
        $slug = $this->uri->segment(3);
        if ($slug) {
            $q = urldecode($this->input->get('q', TRUE));
            $start = intval($this->input->get('start'));

            if ($q <> '') {
                $config['base_url'] = base_url() . 'web/categories/' . $slug . '?q=' . urlencode($q);
                $config['first_url'] = base_url() . 'web/categories/' . $slug . '?q=' . urlencode($q);
            } else {
                $config['base_url'] = base_url() . 'web/categories/' . $slug;
                $config['first_url'] = base_url() . 'web/categories/' . $slug;
            }

            $config['per_page'] = $this->config->item('site_limit_post');
            $config['page_query_string'] = TRUE;
            $config['total_rows'] = $this->Posts_model->total_rows_slug_category(self::$type, $slug, array('poststatus' => 1));

            $posts = $this->Posts_model->get_limit_data_slug_category(self::$type, $slug, $config['per_page'], $start, array('poststatus = ' => 1));

            $category = $this->Categories_model->get_by_slug($slug);
            $categories = $this->Categories_model->get_all();
            $popular = $this->Posts_model->get_popular_posts(self::$type, $this->config->item('site_limit_post'), 0, array('poststatus' => 1));
            $latestpost = $this->Posts_model->get_limit_data(self::$type, $this->config->item('site_limit_post'), 0, NULL, array('poststatus' => 1));

            $this->load->library('pagination');
            $this->pagination->initialize($config);

            $data = array(
                'posts' => $posts,
                'popular' => $popular,
                'categories' => $categories,
                'category' => $category,
                "latestpost" => $latestpost,
                'q' => $q,
                'pagination' => $this->pagination->create_links(),
                'total_rows' => $config['total_rows'],
                'start' => $start,
                'template' => 'posts',
                'extracss' => 'base/posts_extracss'
            );
            $this->load->view('base/content', $data);
        } else {
            redirect(site_url('web/errors'));
        }
    }

}

/* End of file Categories.php */
/* Location: ./application/controllers/Categories.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-02-22 06:11:03 */
/* http://harviacode.com */