<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Icons extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Icons_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'icons/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'icons/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'icons/index.html';
            $config['first_url'] = base_url() . 'icons/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Icons_model->total_rows($q);
        $icons = $this->Icons_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'icons_data' => $icons,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('icons/icons_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Icons_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'icon' => $row->icon,
		'unicode' => $row->unicode,
	    );
            $this->load->view('icons/icons_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('icons'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('icons/create_action'),
	    'id' => set_value('id'),
	    'icon' => set_value('icon'),
	    'unicode' => set_value('unicode'),
	);
        $this->load->view('icons/icons_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'icon' => $this->input->post('icon',TRUE),
		'unicode' => $this->input->post('unicode',TRUE),
	    );

            $this->Icons_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('icons'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Icons_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('icons/update_action'),
		'id' => set_value('id', $row->id),
		'icon' => set_value('icon', $row->icon),
		'unicode' => set_value('unicode', $row->unicode),
	    );
            $this->load->view('icons/icons_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('icons'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'icon' => $this->input->post('icon',TRUE),
		'unicode' => $this->input->post('unicode',TRUE),
	    );

            $this->Icons_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('icons'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Icons_model->get_by_id($id);

        if ($row) {
            $this->Icons_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('icons'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('icons'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('icon', 'icon', 'trim|required');
	$this->form_validation->set_rules('unicode', 'unicode', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Icons.php */
/* Location: ./application/controllers/Icons.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-09-02 04:30:08 */
/* http://harviacode.com */