<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Hargatiket_model extends CI_Model
{

    public $table = 'hargatiket';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($where, $q = NULL)
    {
        $this->db->select('h.*,p.namaperusahaan,k.namakelas,r.kotaasal,r.kotatujuan');
        $this->db->from('hargatiket h');
        $this->db->join('perusahaan p', 'p.id = h.perusahaan', 'left');
        $this->db->join('kelas k', 'k.id=h.jenistiket', 'left');
        $this->db->join('rute r', 'r.id=h.rute','left');
        $this->db->where($where);
        $this->db->group_start();
        $this->db->like('h.id', $q);
        $this->db->or_like('h.jenistiket', $q);
        $this->db->or_like('h.perusahaan', $q);
        $this->db->or_like('h.harga', $q);
        $this->db->or_like('h.createdat', $q);
        $this->db->or_like('h.createdby', $q);
        $this->db->or_like('h.updatedat', $q);
        $this->db->or_like('h.updatedby', $q);
        $this->db->or_like('p.namaperusahaan', $q);
        $this->db->or_like('k.namakelas');
        $this->db->or_like('r.kotaasal');
        $this->db->or_like('r.kotatujuan');
        $this->db->group_end();
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $where, $start = 0, $q = NULL)
    {
        $this->db->select('h.*,p.namaperusahaan,k.namakelas,r.kotaasal,r.kotatujuan');
        $this->db->from('hargatiket h');
        $this->db->join('perusahaan p', 'p.id = h.perusahaan', 'left');
        $this->db->join('kelas k', 'k.id=h.jenistiket', 'left');
        $this->db->join('rute r', 'r.id=h.rute','left');
        $this->db->where($where);
        $this->db->group_start();
        $this->db->like('h.id', $q);
        $this->db->or_like('h.jenistiket', $q);
        $this->db->or_like('h.perusahaan', $q);
        $this->db->or_like('h.harga', $q);
        $this->db->or_like('h.createdat', $q);
        $this->db->or_like('h.createdby', $q);
        $this->db->or_like('h.updatedat', $q);
        $this->db->or_like('h.updatedby', $q);
        $this->db->or_like('p.namaperusahaan', $q);
        $this->db->or_like('k.namakelas');
        $this->db->or_like('r.kotaasal');
        $this->db->or_like('r.kotatujuan');
        $this->db->group_end();
        $this->db->limit($limit, $start);
        return $this->db->get()->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Hargatiket_model.php */
/* Location: ./application/models/Hargatiket_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-09-14 14:19:59 */
/* http://harviacode.com */